version: '3.0'
services:
  hotelbk-db:
    image: mysql:8.0.26
    container_name: hotelbk-db-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fireice22072001
      MYSQL_DATABASE: hotelBK
      MYSQL_USER: linh
      MYSQL_PASSWORD: fireice22072001
    restart: always
    networks:
     -  hotelbk-networks
  hotelbk:
    restart: always
    container_name: hotelbk-container
    image: nhlinh2207/hotelbk:1
    ports:
      - "8081:8080"
    depends_on:
      - hotelbk-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://hotelbk-db-container:3306/hotelBK?CreateDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: linh
      SPRING_DATASOURCE_PASSWORD: fireice22072001
    networks:
      - hotelbk-networks
networks:
    hotelbk-networks:       